name: Main trigger

on:
  schedule:
    - cron: '00 22 * * *' # AM 07:00, KST
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: "Make a choice"
        required: false
        default: 'all'
        options:
          - all
          - Wonny
          - Belty
          - Bolby

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute python script
        run: python src/main.py
