name: Main trigger

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: false
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute python script
        run: python src/main.py
