name: Main trigger

on:
  schedule:
    - cron: '00 22 * * *' # AM 07:00, KST
  workflow_dispatch:
    inputs:
      persona:
        type: choice
        description: "Choose Jellys"
        required: false
        default: 'Wonny'
        options:
          - Wonny
          - Belty
          - Bolby
env:
  PERSONA: ${{ github.event.inputs.persona }}
  BLOG_NAME: ${{ secrets.BLOG_NAME }}
  NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
  NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
  TISTORY_ACCESS_TOKEN: ${{ secrets.TISTORY_ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          echo $BLOG_NAME

      - name: execute python script
        run: python src/goldminer/automations/a1.py
