name: Test

on:
  workflow_dispatch:
    inputs:
      persona:
        type: choice
        description: "Choose Jellys"
        required: false
        default: 'Wonny'
        options:
          - Wonny
          - Belty
          - Bolby
env:
  PERSONA: ${{ github.event.inputs.persona }}
jobs:
  build:
    environment: goldminer
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: Secret to File
        uses: mobiledevops/secret-to-file-action@v1
        with:
          base64-encoded-secret: ${{ secrets.TEST_JSON }}
          filename: my_test.json
          is-executable: false
          working-director: "./"

      - name: test code
        run: |
          echo "Datetime"
          date
          echo "Saved file"
          cat ./my_test.json
          echo "End of File"
